services:
   dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    command: sleep infinity
    volumes:
      - ..:/workspace/07-rest-web
    ports:
      - 3000:3000
    depends_on:
      - postgres-db

   postgres-db:
    image: postgres:15.3
    restart: always
    env_file: ../.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432